core/routes/admin.php
            Route::post('automatic/deactivate', 'GatewayController@deactivate')->name('automatic.deactivate');



            // Manual Methods
            Route::get('manual', 'ManualGatewayController@index')->name('manual.index');
            Route::get('manual/new', 'ManualGatewayController@create')->name('manual.create');
            Route::post('manual/new', 'ManualGatewayController@store')->name('manual.store');
            Route::get('manual/edit/{alias}', 'ManualGatewayController@edit')->name('manual.edit');
            Route::post('manual/update/{id}', 'ManualGatewayController@update')->name('manual.update');
            Route::post('manual/activate', 'ManualGatewayController@activate')->name('manual.activate');
            Route::post('manual/deactivate', 'ManualGatewayController@deactivate')->name('manual.deactivate');
        });


        // DEPOSIT SYSTEM
        Route::name('deposit.')->prefix('deposit')->group(function(){
            Route::get('/', 'DepositController@deposit')->name('list');
            Route::get('pending', 'DepositController@pending')->name('pending');
            Route::get('rejected', 'DepositController@rejected')->name('rejected');
            Route::get('approved', 'DepositController@approved')->name('approved');
            Route::get('successful', 'DepositController@successful')->name('successful');
            Route::get('details/{id}', 'DepositController@details')->name('details');

            Route::post('reject', 'DepositController@reject')->name('reject');
            Route::post('approve', 'DepositController@approve')->name('approve');
            Route::get('via/{method}/{type?}', 'DepositController@depViaMethod')->name('method');
            Route::get('/{scope}/search', 'DepositController@search')->name('search');
            Route::get('date-search/{scope}', 'DepositController@dateSearch')->name('dateSearch');

        });


        // WITHDRAW SYSTEM
        Route::name('withdraw.')->prefix('withdraw')->group(function(){
            Route::get('pending', 'WithdrawalController@pending')->name('pending');
            Route::get('approved', 'WithdrawalController@approved')->name('approved');
            Route::get('rejected', 'WithdrawalController@rejected')->name('rejected');
            Route::get('log', 'WithdrawalController@log')->name('log');
            Route::get('via/{method_id}/{type?}', 'WithdrawalController@logViaMethod')->name('method');
            Route::get('{scope}/search', 'WithdrawalController@search')->name('search');
            Route::get('date-search/{scope}', 'WithdrawalController@dateSearch')->name('dateSearch');
            Route::get('details/{id}', 'WithdrawalController@details')->name('details');
            Route::post('approve', 'WithdrawalController@approve')->name('approve');
            Route::post('reject', 'WithdrawalController@reject')->name('reject');


            // Withdraw Method
            Route::get('method/', 'WithdrawMethodController@methods')->name('method.index');
            Route::get('method/create', 'WithdrawMethodController@create')->name('method.create');
            Route::post('method/create', 'WithdrawMethodController@store')->name('method.store');
            Route::get('method/edit/{id}', 'WithdrawMethodController@edit')->name('method.edit');
            Route::post('method/edit/{id}', 'WithdrawMethodController@update')->name('method.update');
            Route::post('method/activate', 'WithdrawMethodController@activate')->name('method.activate');
            Route::post('method/deactivate', 'WithdrawMethodController@deactivate')->name('method.deactivate');
        });

        // Report
        Route::get('report/transaction', 'ReportController@transaction')->name('report.transaction');
        Route::get('report/transaction/search', 'ReportController@transactionSearch')->name('report.transaction.search');
        Route::get('report/login/history', 'ReportController@loginHistory')->name('report.login.history');
        Route::get('report/login/ipHistory/{ip}', 'ReportController@loginIpHistory')->name('report.login.ipHistory');


        // Admin Support
        Route::get('tickets', 'SupportTicketController@tickets')->name('ticket');
        Route::get('tickets/pending', 'SupportTicketController@pendingTicket')->name('ticket.pending');
        Route::get('tickets/closed', 'SupportTicketController@closedTicket')->name('ticket.closed');
        Route::get('tickets/answered', 'SupportTicketController@answeredTicket')->name('ticket.answered');
        Route::get('tickets/view/{id}', 'SupportTicketController@ticketReply')->name('ticket.view');
        Route::post('ticket/reply/{id}', 'SupportTicketController@ticketReplySend')->name('ticket.reply');
        Route::get('ticket/download/{ticket}', 'SupportTicketController@ticketDownload')->name('ticket.download');
        Route::post('ticket/delete', 'SupportTicketController@ticketDelete')->name('ticket.delete');


        // Language Manager
        Route::get('/language', 'LanguageController@langManage')->name('language.manage');
        Route::post('/language', 'LanguageController@langStore')->name('language.manage.store');
        Route::post('/language/delete/{id}', 'LanguageController@langDel')->name('language.manage.del');
        Route::post('/language/update/{id}', 'LanguageController@langUpdatepp')->name('language.manage.update');
        Route::get('/language/edit/{id}', 'LanguageController@langEdit')->name('language.key');
        Route::post('/language/import', 'LanguageController@langImport')->name('language.import_lang');



        Route::post('language/store/key/{id}', 'LanguageController@storeLanguageJson')->name('language.store.key');
        Route::post('language/delete/key/{id}', 'LanguageController@deleteLanguageJson')->name('language.delete.key');
        Route::post('language/update/key/{id}', 'LanguageController@updateLanguageJson')->name('language.update.key');



        // General Setting
        Route::get('general-setting', 'GeneralSettingController@index')->name('setting.index');
        Route::post('general-setting', 'GeneralSettingController@update')->name('setting.update');

        // Logo-Icon
        Route::get('setting/logo-icon', 'GeneralSettingController@logoIcon')->name('setting.logo_icon');
        Route::post('setting/logo-icon', 'GeneralSettingController@logoIconUpdate')->name('setting.logo_icon');

        // Plugin
        Route::get('extensions', 'ExtensionController@index')->name('extensions.index');
        Route::post('extensions/update/{id}', 'ExtensionController@update')->name('extensions.update');
        Route::post('extensions/activate', 'ExtensionController@activate')->name('extensions.activate');
        Route::post('extensions/deactivate', 'ExtensionController@deactivate')->name('extensions.deactivate');


        // Email Setting
        Route::get('email-template/global', 'EmailTemplateController@emailTemplate')->name('email.template.global');
        Route::post('email-template/global', 'EmailTemplateController@emailTemplateUpdate')->name('email.template.global');
        Route::get('email-template/setting', 'EmailTemplateController@emailSetting')->name('email.template.setting');
        Route::post('email-template/setting', 'EmailTemplateController@emailSettingUpdate')->name('email.template.setting');
        Route::get('email-template/index', 'EmailTemplateController@index')->name('email.template.index');
        Route::get('email-template/{id}/edit', 'EmailTemplateController@edit')->name('email.template.edit');
        Route::post('email-template/{id}/update', 'EmailTemplateController@update')->name('email.template.update');
        Route::post('email-template/send-test-mail', 'EmailTemplateController@sendTestMail')->name('email.template.sendTestMail');


        // SMS Setting
        Route::get('sms-template/global', 'SmsTemplateController@smsSetting')->name('sms.template.global');
        Route::post('sms-template/global', 'SmsTemplateController@smsSettingUpdate')->name('sms.template.global');
        Route::get('sms-template/index', 'SmsTemplateController@index')->name('sms.template.index');
        Route::get('sms-template/edit/{id}', 'SmsTemplateController@edit')->name('sms.template.edit');
        Route::post('sms-template/update/{id}', 'SmsTemplateController@update')->name('sms.template.update');
        Route::post('email-template/send-test-sms', 'SmsTemplateController@sendTestSMS')->name('sms.template.sendTestSMS');

        // SEO
        Route::get('seo', 'FrontendController@seoEdit')->name('seo');


        // Frontend
        Route::name('frontend.')->prefix('frontend')->group(function () {


            Route::get('templates', 'FrontendController@templates')->name('templates');
            Route::post('templates', 'FrontendController@templatesActive')->name('templates.active');



            Route::get('frontend-sections/{key}', 'FrontendController@frontendSections')->name('sections');
            Route::post('frontend-content/{key}', 'FrontendController@frontendContent')->name('sections.content');
            Route::get('frontend-element/{key}/{id?}', 'FrontendController@frontendElement')->name('sections.element');
            Route::post('remove', 'FrontendController@remove')->name('remove');

            // Page Builder
            Route::get('manage-pages', 'PageBuilderController@managePages')->name('manage.pages');
            Route::post('manage-pages', 'PageBuilderController@managePagesSave')->name('manage.pages.save');
            Route::post('manage-pages/update', 'PageBuilderController@managePagesUpdate')->name('manage.pages.update');
            Route::post('manage-pages/delete', 'PageBuilderController@managePagesDelete')->name('manage.pages.delete');
            Route::get('manage-section/{id}', 'PageBuilderController@manageSection')->name('manage.section');

core/routes/web.php
        Route::get('email-template/global', 'EmailTemplateController@emailTemplate')->name('email.template.global');
        Route::post('email-template/global', 'EmailTemplateController@emailTemplateUpdate')->name('email.template.global');
        Route::get('email-template/setting', 'EmailTemplateController@emailSetting')->name('email.template.setting');
        Route::post('email-template/setting', 'EmailTemplateController@emailSettingUpdate')->name('email.template.setting');
        Route::get('email-template/index', 'EmailTemplateController@index')->name('email.template.index');
        Route::get('email-template/{id}/edit', 'EmailTemplateController@edit')->name('email.template.edit');
        Route::post('email-template/{id}/update', 'EmailTemplateController@update')->name('email.template.update');
        Route::post('email-template/send-test-mail', 'EmailTemplateController@sendTestMail')->name('email.template.sendTestMail');


        // SMS Setting
        Route::get('sms-template/global', 'SmsTemplateController@smsSetting')->name('sms.template.global');
        Route::post('sms-template/global', 'SmsTemplateController@smsSettingUpdate')->name('sms.template.global');
        Route::get('sms-template/index', 'SmsTemplateController@index')->name('sms.template.index');
        Route::get('sms-template/edit/{id}', 'SmsTemplateController@edit')->name('sms.template.edit');
        Route::post('sms-template/update/{id}', 'SmsTemplateController@update')->name('sms.template.update');
        Route::post('email-template/send-test-sms', 'SmsTemplateController@sendTestSMS')->name('sms.template.sendTestSMS');

        // Exchange
        Route::get('exchange', 'ExchangeController@index')->name('exchange');
        Route::post('exchange/reject/{id}', 'ExchangeController@reject')->name('exchange.reject');
        Route::post('exchange/accept/{id}', 'ExchangeController@verify')->name('exchange.accept');

        Route::get('delivery', 'DeliveryController@index')->name('delivery');
        Route::get('export_delivery', 'DeliveryController@export')->name('export.delivery');
        
        Route::post('delivery/deliver', 'DeliveryController@delivery')->name('deliver.deliver');
        Route::get('bro_delivery', 'BrodevController@index')->name('BroDelivery');
        Route::get('bro_delivery/pickup', 'BrodevController@index2')->name('BroDelivery.pickup');
        Route::post('bro_delivery/deliver', 'BrodevController@delivery')->name('BroDeliver.deliver');
        Route::get('brodev/search_delivery', 'BrodevController@search')->name('BroDelivery.search');
        Route::get('brodev/search_pickup', 'BrodevController@search2')->name('BroDelivery.search2');
        Route::get('export_bro_delivery', 'BrodevController@export')->name('export.BROdelivery');
        Route::get('export_bro_pickup', 'BrodevController@export2')->name('export.BROpickup');
        
        Route::post('resend/email/{user_id}/{brodevtrx}', 'BrodevController@resendEmail')->name('resend.email');

        // SEO
        Route::get('seo', 'FrontendController@seoEdit')->name('seo');


        // Frontend
        Route::name('frontend.')->prefix('frontend')->group(function () {

            Route::get('templates', 'FrontendController@templates')->name('templates');
            Route::post('templates', 'FrontendController@templatesActive')->name('templates.active');

            Route::get('frontend-sections/{key}', 'FrontendController@frontendSections')->name('sections');
            Route::post('frontend-content/{key}', 'FrontendController@frontendContent')->name('sections.content');
            Route::get('frontend-element/{key}/{id?}', 'FrontendController@frontendElement')->name('sections.element');
            Route::post('remove', 'FrontendController@remove')->name('remove');

            // Page Builder
            Route::get('manage-pages', 'PageBuilderController@managePages')->name('manage.pages');
            Route::post('manage-pages', 'PageBuilderController@managePagesSave')->name('manage.pages.save');
            Route::post('manage-pages/update', 'PageBuilderController@managePagesUpdate')->name('manage.pages.update');
            Route::post('manage-pages/delete', 'PageBuilderController@managePagesDelete')->name('manage.pages.delete');
            Route::get('manage-section/{id}', 'PageBuilderController@manageSection')->name('manage.section');
            Route::post('manage-section/{id}', 'PageBuilderController@manageSectionUpdate')->name('manage.section.update');
        });
    });
});




/*
|--------------------------------------------------------------------------
| Start User Area
|--------------------------------------------------------------------------
*/


Route::name('user.')->group(function () {
    Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
    Route::post('/login', 'Auth\LoginController@login');
    Route::get('logout', 'Auth\LoginController@logout')->name('logout');

    Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
    Route::post('register', 'Auth\RegisterController@register')->middleware('regStatus');


    Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('password/code-verify', 'Auth\ForgotPasswordController@codeVerify')->name('password.code_verify');
    Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');
    Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/verify-code', 'Auth\ForgotPasswordController@verifyCode')->name('password.verify-code')->middleware('throttle:5,120');;
});


Route::name('user.')->prefix('user')->group(function () {

    Route::get('/Product', 'ProductController@productIndex')->name('product.index');
    Route::get('/Product/detail/{id}', 'ProductController@productDetail')->name('product.detail');

    Route::middleware('auth')->group(function () {
        Route::get('authorization', 'AuthorizationController@authorizeForm')->name('authorization');
        Route::get('resend-verify', 'AuthorizationController@sendVerifyCode')->name('send_verify_code');
        Route::post('verify-email', 'AuthorizationController@emailVerification')->name('verify_email');
        Route::post('verify-sms', 'AuthorizationController@smsVerification')->name('verify_sms');
        Route::post('verify-g2fa', 'AuthorizationController@g2faVerification')->name('go2fa.verify');

        Route::middleware(['checkStatus'])->group(function () {
            Route::get('dashboard', 'UserController@home')->name('home');
            Route::get('referals', 'UserController@ref')->name('ref.tree');

            Route::get('profile-setting', 'UserController@profile')->name('profile-setting');
            Route::post('profile-setting', 'UserController@submitProfile');
            Route::post('edit_rekening', 'UserController@edit_rekening')->name('edit_rekening');
            Route::post('add_rekening', 'UserController@add_rekening')->name('add_rekening');
            Route::get('change-password', 'UserController@changePassword')->name('change-password');
            Route::post('change-password', 'UserController@submitPassword');

            Route::post('add_address', 'AlamatController@add_address')->name('add_address');
            Route::post('edit_address', 'AlamatController@edit_address')->name('edit_address');

            //Claim Free Bro
            Route::post('/claim', 'UserController@claimBro')->name('claimbro');
            Route::post('/claimbro', 'UserController@claimBro2')->name('claimbro2');

            Route::get('reward', 'UrewardController@userReward')->name('reward');
            Route::get('reward/print/{trx}', 'UrewardController@printTicket')->name('ticket.print');
            //Claimreward
            Route::post('claim_reward/{id}', 'UrewardController@claimReward')->name('claim.reward');
            Route::post('claim_rewardup/{id}', 'UrewardController@claimRewardUp')->name('claim.rewardup');

            //2FA
            Route::get('twofactor', 'UserController@show2faForm')->name('twofactor');
            Route::post('twofactor/enable', 'UserController@create2fa')->name('twofactor.enable');
            Route::post('twofactor/disable', 'UserController@disable2fa')->name('twofactor.disable');
            Route::get('login/history', 'UserController@userLoginHistory')->name('login.history');

            //plan
            Route::get('/plan', 'PlanController@planIndex')->name('plan.index');
            Route::get('/plan/bro-pack-select/bro-{user}-{trx}', 'PlanController@selectType')->name('plan.select.type');
            Route::post('/plan/bro-pack-select/sumbit', 'PlanController@selectTypeSubmit')->name('plan.select.submit');

            // Route::get('/Product', 'ProductController@productIndex')->name('product.index');
            Route::get('/Product-special/{bro}', 'ProductController@productSpecial')->name('product.product_special');
            
            // Route::post('/plan', 'PlanController@planStore')->name('plan.purchase');
            Route::get('/referral-log', 'UserController@referralCom')->name('referral.log');

            // Route::get('/binary-log', 'PlanController@binaryCom')->name('binary.log');
            Route::get('/binary-summery', 'PlanController@binarySummery')->name('binary.summery');
            Route::get('/bv-log', 'PlanController@bvlog')->name('bv.log');
            // Route::get('/referrals', 'PlanController@myRefLog')->name('my.ref');
            Route::get('/tree', 'PlanController@myTree')->name('my.tree');
            Route::get('/tree/{user}', 'PlanController@otherTree')->name('other.tree');
            Route::get('/tree/search', 'PlanController@otherTree')->name('other.tree.search');

core/resources/views/templates/basic/sections/about.blade.php
@php
    $about = getContent('about.content',true);
    $aboutData = getContent('about.element', false, null, true);
@endphp

<!-- About Section -->
<section class="about-section pt-120 pb-60">
    <div class="container">
        <div class="row justify-content-between flex-wrap-reverse gy-4">
            <div class="col-lg-6">
                <div class="about__thumb">
                    <div class="thumb">
                        <img src="{{ getImage('assets/images/frontend/about/'.@$about->data_values->background_image, '800x530') }}" alt="@lang('about')">
                        <a href="{{ @$about->data_values->video_link}}" class="video-button" data-lightbox><i class="las la-play"></i></a>
                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="ps-xl-4 ps-xxl-5">
                    <div class="about-content">
                        <div class="section__header">
                            <span class="section__cate">{{ __(@$about->data_values->heading) }}</span>
                            <h3 class="section__title">{{ __(@$about->data_values->subheading) }}</h3>
                            <p>@php echo @$about->data_values->description; @endphp</p>
                        </div>
                        <div class="row g-4">
                            @foreach($aboutData as $data)
                                <div class="col-lg-6 col-md-6 col-sm-12">
                                    <div class="about__item">
                                        <div class="icon">
                                            @php echo @$data->data_values->icon; @endphp
                                        </div>
                                        <div class="info">
                                            <h6 class="subtitle">{{ __(@$data->data_values->paragraph) }}</h6>
                                        </div>
                                    </div>
                                </div>
                            @endforeach
                        </div>
                        <div class="btn__grp">
                            <a href="{{__(@$about->data_values->left_button_link)}}" class="cmn--btn">{{__(@$about->data_values->left_button)}}</a>
                            <a href="{{__(@$about->data_values->right_button_link)}}" class="cmn--btn">{{__(@$about->data_values->right_button)}}</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section> 
<!-- About Section -->

core/resources/views/templates/basic/sections/blog.blade.php
@php
    $blogCaption = getContent('blog.content',true);
    $blogs = getContent('blog.element',false,3);
@endphp

<!-- Blog Section -->
<section class="blog-section pt-60 pb-120">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-6 col-md-10">
                <div class="section__header text-center">
                    <span class="section__cate">{{ __(@$blogCaption->data_values->heading) }}</span>
                    <h3 class="section__title">{{ __(@$blogCaption->data_values->subheading) }}</h3>
                    <p>
                        {{ __(@$blogCaption->data_values->description) }}
                    </p>
                </div>
            </div>
        </div>
        <div class="row g-4 justify-content-center">

            @foreach($blogs as $blog)
                <div class="col-lg-4 col-md-6 col-sm-10">
                    <div class="post__item">
                        <div class="post__thumb">
                            <a href="{{route('singleBlog', [slug(@$blog->data_values->title), $blog])}}">
                                <img src="{{ getImage('assets/images/frontend/blog/thumb_'.@$blog->data_values->blog_image, '600x300') }}" alt="@lang('blog')">
                            </a>
                            <div class="post__date">
                                <h4 class="date">{{showDateTime($blog->created_at, 'd')}}</h4>
                                <span>{{showDateTime($blog->created_at, 'M')}}</span>
                            </div>
                        </div>
                        <div class="post__content">
                            <div class="overflow-hidden">
                                <div class="post__meta">
                                    <a class="item">
                                        <i class="las la-user"></i>
                                        <span>@lang('Admin')</span>
                                    </a>
                                </div>
                            </div>
                            <h5 class="post__title">
                                <a href="{{route('singleBlog', [slug(@$blog->data_values->title), $blog])}}">{{ __(@$blog->data_values->title) }}</a>
                            </h5>
                            <a href="{{route('singleBlog', [slug(@$blog->data_values->title), $blog])}}" class="text--base">@lang('Read More') <i class="las la-long-arrow-alt-right"></i></a>
                        </div>
                    </div>
                </div>
            @endforeach

        </div>
    </div>
</section>
<!-- Blog Section -->

core/resources/views/templates/basic/sections/mlm_plan.blade.php
@php
    $planTitle = getContent('mlm_plan.content', true);
    $plans = \App\Models\Plan::where('status', 1)->get();
@endphp

<div class="cmn--modal modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">@lang("Business Volume (BV) info")</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <span>
                    @lang('When someone from your below tree subscribe this plan, You will get this Business Volume  which will be used for matching bonus')
                </span>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn--danger" data-bs-dismiss="modal">@lang('Close')</button>
            </div>
        </div>
    </div>
</div>

<div class="cmn--modal modal fade" id="exampleModal2" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">@lang('Referral Commission info')</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <span>
                    @lang('When Your Direct-Referred/Sponsored  User Subscribe in') <b> @lang('ANY PLAN') </b>, @lang('You will get this amount')
                </span>
                <p class="text-success mt-4"> @lang('This is the reason You should Choose a Plan With Bigger Referral Commission')</p> 
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn--danger" data-bs-dismiss="modal">@lang('Close')</button>
            </div>
        </div>
    </div>
</div>

<div class="cmn--modal modal fade" id="exampleModal3" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">@lang('Commission to tree info')</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <span>
                    @lang('When someone from your below tree subscribe this plan, You will get this amount as Tree Commission')
                </span>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn--danger" data-bs-dismiss="modal">@lang('Close')</button>
            </div>
        </div>
    </div>
</div>

<!-- Pricing Plan Section -->
<section class="pricing-section pt-120 pb-60">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-6 col-md-10">
                <div class="section__header text-center">
                    <span class="section__cate">{{ __(@$planTitle->data_values->heading) }}</span>
                    <h3 class="section__title">{{ __(@$planTitle->data_values->subheading) }}</h3>
                    <p>
                        {{ __(@$planTitle->data_values->description) }}
                    </p>
                </div>
            </div>
        </div>
        <div class="price-wrapper">

            @foreach($plans  as $plan)
                <div class="pricing-item">
                    <div class="pricing-deco">
                        <div class="wave">&nbsp;</div>
                            <div class="pricing-price"><span class="pricing-currency">{{$general->cur_sym}}</span>{{getAmount($plan->price)}}
                        </div>
                        <h3 class="pricing-title">{{__(@$plan->name)}}</h3>
                    </div>
                    <ul class="pricing-feature-list">
                        <li class="pricing-feature">
                            @lang('Business Volume') (@lang('BV')) : <span class="amount">{{$plan->bv}}
                            <span data-bs-target="#exampleModal" data-bs-toggle="modal"><i class="fas la-question"></i></span>
                        </li>
                        <li class="pricing-feature">
                            @lang('Referral Commission') : <span class="amount">{{$general->cur_sym}} {{getAmount($plan->ref_com)}}
                            <span data-bs-target="#exampleModal2" data-bs-toggle="modal"><i class="fas la-question"></i></span>
                        </li>
                        <li class="pricing-feature">
                            @lang('Commission To Tree') : <span class="amount">{{$general->cur_sym}} {{getAmount($plan->tree_com)}}
                            <span data-bs-target="#exampleModal3" data-bs-toggle="modal"><i class="fas la-question"></i></span>
                        </li>
                    </ul>
                    <div class="text-center pb-4 mb-2">
                        <a class="cmn--btn" href="{{route('user.plan.index')}}">@lang('Subscribe now')</a>
                    </div>
                </div>
            @endforeach

        </div>
    </div>
</section>
<!-- Pricing Plan Section -->
 